# Prefix API
SERVERS_PREFIX = '/servers'

# Endpoint API completi
REGISTER_NEW_SERVER_API_ENDPOINT = f'{SERVERS_PREFIX}/register'
PUBLISH_RESULT_API_ENDPOINT = f'{SERVERS_PREFIX}/results'
GET_SERVER_KEY_API_ENDPOINT = f'{SERVERS_PREFIX}/key'
